title: Emojis
description: "CSS emoji classes and utilities"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed
exclude:
  - Gemfile
  - Rakefile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE.md
include: 
  - _pages